#!/usr/bin/env bash
# Generate firmware/sentinel-node/include/secrets.h for one node (gitignored, never commit it).
#   BROKER_HOST=host.wokwi.internal ./firmware-secrets.sh sentinel-01
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
OUT="$HERE/out"
id="${1:?usage: $0 <node-id>}"
BROKER_HOST="${BROKER_HOST:-host.wokwi.internal}"
BROKER_PORT="${BROKER_PORT:-8883}"
DEST="$HERE/../../firmware/sentinel-node/include/secrets.h"

[[ -f "$OUT/$id/$id.crt" ]] || { echo "no cert for $id, run: ./pki.sh device $id" >&2; exit 1; }
mkdir -p "$(dirname "$DEST")"

pem() { printf 'R"PEM(\n%s\n)PEM"' "$(cat "$1")"; }

{
  echo "// GENERATED by infra/pki/firmware-secrets.sh for node '$id'. DO NOT COMMIT."
  echo "#pragma once"
  echo "#define ARGUS_NODE_ID \"$id\""
  echo "#define ARGUS_BROKER_HOST \"$BROKER_HOST\""
  echo "#define ARGUS_BROKER_PORT $BROKER_PORT"
  echo "#define ARGUS_HMAC_KEY_HEX \"$(cat "$OUT/$id/$id.hmac")\""
  echo "static const char ARGUS_CA_CERT[] = $(pem "$OUT/ca.crt");"
  echo "static const char ARGUS_CLIENT_CERT[] = $(pem "$OUT/$id/$id.crt");"
  echo "static const char ARGUS_CLIENT_KEY[] = $(pem "$OUT/$id/$id.key");"
} > "$DEST"
echo "wrote $DEST (broker $BROKER_HOST:$BROKER_PORT)"
